"""mcp oauth columns + per-user connections

Revision ID: 768f825373c1
Revises: 1f73cc0a0608
Create Date: 2026-07-04 05:07:21.361204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '768f825373c1'
down_revision: Union[str, Sequence[str], None] = '1f73cc0a0608'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mcp_connections', sa.Column('auth_type', sa.String(length=20), nullable=True))
    op.add_column('mcp_connections', sa.Column('refresh_token_enc', sa.Text(), nullable=True))
    op.add_column('mcp_connections', sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('mcp_connections', sa.Column('oauth_client_id', sa.String(length=300), nullable=True))
    op.add_column('mcp_connections', sa.Column('oauth_client_secret_enc', sa.Text(), nullable=True))
    op.add_column('mcp_connections', sa.Column('oauth_token_endpoint', sa.String(length=500), nullable=True))
    op.add_column('mcp_connections', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('uq_mcp_company_app'), 'mcp_connections', type_='unique')
    op.create_index(op.f('ix_mcp_connections_owner_id'), 'mcp_connections', ['owner_id'], unique=False)
    op.create_unique_constraint('uq_mcp_company_app_owner', 'mcp_connections', ['company_id', 'app', 'owner_id'])
    op.create_foreign_key('fk_mcp_connections_owner', 'mcp_connections', 'employees', ['owner_id'], ['id'], ondelete='CASCADE')
    op.execute("UPDATE mcp_connections SET auth_type='token' WHERE auth_type IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_mcp_connections_owner', 'mcp_connections', type_='foreignkey')
    op.drop_constraint('uq_mcp_company_app_owner', 'mcp_connections', type_='unique')
    op.drop_index(op.f('ix_mcp_connections_owner_id'), table_name='mcp_connections')
    op.create_unique_constraint(op.f('uq_mcp_company_app'), 'mcp_connections', ['company_id', 'app'], postgresql_nulls_not_distinct=False)
    op.drop_column('mcp_connections', 'owner_id')
    op.drop_column('mcp_connections', 'oauth_token_endpoint')
    op.drop_column('mcp_connections', 'oauth_client_secret_enc')
    op.drop_column('mcp_connections', 'oauth_client_id')
    op.drop_column('mcp_connections', 'token_expires_at')
    op.drop_column('mcp_connections', 'refresh_token_enc')
    op.drop_column('mcp_connections', 'auth_type')
    # ### end Alembic commands ###
