"""contract baseline_snapshot

Revision ID: 81aa6d45b951
Revises: 768f825373c1
Create Date: 2026-07-04 06:59:53.939178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81aa6d45b951'
down_revision: Union[str, Sequence[str], None] = '768f825373c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('baseline_snapshot', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'baseline_snapshot')
    # ### end Alembic commands ###
