"""mcp fail_count

Revision ID: 97c0ea18f9e2
Revises: 81aa6d45b951
Create Date: 2026-07-07 04:28:38.208474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97c0ea18f9e2'
down_revision: Union[str, Sequence[str], None] = '81aa6d45b951'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mcp_connections', sa.Column('fail_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mcp_connections', 'fail_count')
    # ### end Alembic commands ###
